# Generated by Django 4.2.6 on 2023-10-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialites',
            new_name='specialities',
        ),
    ]
